//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROBS.U8WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="U8WebService.MStockSoap")]
    public interface MStockSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 cCusCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentStock", ReplyAction="*")]
        GROBS.U8WebService.GetCurrentStockResponse GetCurrentStock(GROBS.U8WebService.GetCurrentStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentStock", ReplyAction="*")]
        System.Threading.Tasks.Task<GROBS.U8WebService.GetCurrentStockResponse> GetCurrentStockAsync(GROBS.U8WebService.GetCurrentStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentStock", Namespace="http://tempuri.org/", Order=0)]
        public GROBS.U8WebService.GetCurrentStockRequestBody Body;
        
        public GetCurrentStockRequest() {
        }
        
        public GetCurrentStockRequest(GROBS.U8WebService.GetCurrentStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cCusCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cInvCode;
        
        public GetCurrentStockRequestBody() {
        }
        
        public GetCurrentStockRequestBody(string cCusCode, string cInvCode) {
            this.cCusCode = cCusCode;
            this.cInvCode = cInvCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public GROBS.U8WebService.GetCurrentStockResponseBody Body;
        
        public GetCurrentStockResponse() {
        }
        
        public GetCurrentStockResponse(GROBS.U8WebService.GetCurrentStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal GetCurrentStockResult;
        
        public GetCurrentStockResponseBody() {
        }
        
        public GetCurrentStockResponseBody(decimal GetCurrentStockResult) {
            this.GetCurrentStockResult = GetCurrentStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MStockSoapChannel : GROBS.U8WebService.MStockSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MStockSoapClient : System.ServiceModel.ClientBase<GROBS.U8WebService.MStockSoap>, GROBS.U8WebService.MStockSoap {
        
        public MStockSoapClient() {
        }
        
        public MStockSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MStockSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MStockSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MStockSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GROBS.U8WebService.GetCurrentStockResponse GROBS.U8WebService.MStockSoap.GetCurrentStock(GROBS.U8WebService.GetCurrentStockRequest request) {
            return base.Channel.GetCurrentStock(request);
        }
        
        public decimal GetCurrentStock(string cCusCode, string cInvCode) {
            GROBS.U8WebService.GetCurrentStockRequest inValue = new GROBS.U8WebService.GetCurrentStockRequest();
            inValue.Body = new GROBS.U8WebService.GetCurrentStockRequestBody();
            inValue.Body.cCusCode = cCusCode;
            inValue.Body.cInvCode = cInvCode;
            GROBS.U8WebService.GetCurrentStockResponse retVal = ((GROBS.U8WebService.MStockSoap)(this)).GetCurrentStock(inValue);
            return retVal.Body.GetCurrentStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GROBS.U8WebService.GetCurrentStockResponse> GROBS.U8WebService.MStockSoap.GetCurrentStockAsync(GROBS.U8WebService.GetCurrentStockRequest request) {
            return base.Channel.GetCurrentStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<GROBS.U8WebService.GetCurrentStockResponse> GetCurrentStockAsync(string cCusCode, string cInvCode) {
            GROBS.U8WebService.GetCurrentStockRequest inValue = new GROBS.U8WebService.GetCurrentStockRequest();
            inValue.Body = new GROBS.U8WebService.GetCurrentStockRequestBody();
            inValue.Body.cCusCode = cCusCode;
            inValue.Body.cInvCode = cInvCode;
            return ((GROBS.U8WebService.MStockSoap)(this)).GetCurrentStockAsync(inValue);
        }
    }
}
